#!/usr/bin/env python

import argparse

# Local package functions
import video_utils

description = ('Clean up video files based on disk free space and video '
               'file name (lowest to highest video file number)')
ap = argparse.ArgumentParser(description=description)
ap.add_argument('-d', '--directory', dest='videos_dir', default='.',
                metavar='dir',
                help='Videos directory (default: current directory)')
ap.add_argument('-p', '--pretend', dest='pretend', action='store_true',
                help='Pretend only (dry run)')
ap.add_argument('-f', '--free-space', dest='free_space', required=True,
                metavar='space (GiB)', type=int,
                help=('Remove video files until there is at least this much '
                      'space available on the disk where the videos directory '
                      'resides'))
args = ap.parse_args()
video_utils.cleanup_videos(args.videos_dir, args.free_space, args.pretend)
